improvin the training pipeline
1) NN module
2) Optim module

Improvements
1) Automatic weights and bias layers with NN module
2) loss function also automatic 
3) sigmoid fxn too 
4) automatic param updation with optim

NN module
wide array of classes and fucntions designed to helpo devs build neural networks efficiently and easily.
has a lot of things 

1) A lot of layers 
2) Activation functions 
3) Loss functions 
4) Container Modules 
5) Regularization and Dropout

In [8]:
#Create Model Class
import torch
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


In [9]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.6888],
        [0.7036],
        [0.6434],
        [0.6523],
        [0.6818],
        [0.5488],
        [0.5740],
        [0.6404],
        [0.5948],
        [0.6696]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.weight

Parameter containing:
tensor([[ 0.4197,  0.1678, -0.1620,  0.4298, -0.1919]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.2401], requires_grad=True)

In [14]:
from torchinfo import summary
summary (model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear1(features)
        out= self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [18]:
model = Model(features.shape[1])
model(features)

tensor([[0.6426],
        [0.6410],
        [0.6300],
        [0.6354],
        [0.6424],
        [0.6207],
        [0.6339],
        [0.6303],
        [0.6269],
        [0.6456]], grad_fn=<SigmoidBackward0>)

In [19]:
model.linear1.weight


Parameter containing:
tensor([[ 0.1195, -0.3900,  0.0878, -0.1897, -0.3554],
        [ 0.3492, -0.4457,  0.4294,  0.3690, -0.1805],
        [-0.0107, -0.1809,  0.1895, -0.2989, -0.1102]], requires_grad=True)

In [20]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3194,  0.0775, -0.2870]], requires_grad=True)

In [ ]:
# sequential container
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),
        )

    def forward(self,features):
        out = self.network(features)
        return out

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2323741257.py, line 6)