In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

In [4]:
a = torch.empty(2,3)  #allocates space in memory

In [5]:
type(a)

torch.Tensor

In [7]:
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3) #bw - and 1

tensor([[0.9649, 0.8923, 0.2601],
        [0.8735, 0.0475, 0.3318]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.tensor([[1,2,3],[1,2,3]])

tensor([[1, 2, 3],
        [1, 2, 3]])

In [18]:
x = torch.tensor([[1,2,3],[1,2,3]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)  #same shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.zeros_like(x) 
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
x
x.dtype

torch.int64

In [28]:
c = torch.tensor([1.0,2.0,3.0] , dtype = torch.int32)
d = torch.tensor([1,2,3] , dtype = torch.float32)

In [31]:
y = x.to(torch.float32)

In [32]:
torch.rand_like(y)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Not really needed to write all the things 

In [ ]:
# inplace ops
'''
new tensors are formed when the operations are performed on existing vectors
so we use inplace
just use underscore 
m.relu_() like this
'''

copying a tensor

In [33]:
a = torch.rand(2,3)

In [34]:
b = a.clone()

In [37]:
id(a)

2588492201824

In [38]:
id(b)

2588347307152

operations on gpu

In [39]:
device = torch.device('cuda')

In [42]:
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [44]:
a = torch.rand(2,3)
a

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [45]:
b = a.to(device)

In [46]:
b

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]], device='cuda:0')

In [47]:
import time

In [50]:
size = 10000
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1 , matrix_cpu2)
cpu_time = time.time() - start_time
print(f"Time on CPU : {cpu_time: .4f} sec")

matrix_gpu1 = matrix_cpu1.to(device) 
matrix_gpu2 = matrix_cpu2.to(device) 
start_time = time.time()
torch.cuda.synchronize()
result_cpu = torch.matmul(matrix_cpu1 , matrix_cpu2)
gpu_time = time.time() - start_time
print(f"Time on GPU : {gpu_time: .4f} sec")



Time on CPU :  6.8254 sec
Time on GPU :  7.0744 sec


In [ ]:
#unsqueeze and squeeze 
# adds another dimension 