In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

In [4]:
a = torch.empty(2,3)  #allocates space in memory

In [5]:
type(a)

torch.Tensor

In [7]:
b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3) #bw - and 1

tensor([[0.9649, 0.8923, 0.2601],
        [0.8735, 0.0475, 0.3318]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[1,2,3]])

TypeError: tensor() takes 1 positional argument but 2 were given